spring.application.name=tinder-ai-backend

spring.mongodb.uri=${DATASOURCE_URL}

spring.ai.openai.base-url=${LLM_BASE_URL}
spring.ai.openai.chat.model=${CHAT_MODEL}
spring.ai.openai.api-key=${LLM_API_KEY}
spring.ai.openai.timeout=${LLM_TIMEOUT}
spring.ai.openai.max-retries=${LLM_MAX_RETRY}

pixazo.api-key=${PIXAZO_API_KEY}

startup-actions.initializeProfiles=${PROFILE_INITIALIZATION_STATUS}
tinderai.lookingForGender=${LOOKING_FOR_GENDER}
tinderai.minAge=${MIN_AGE}
tinderai.maxAge=${MAX_AGE}
tinderai.ethnicities=${ETHNICITIES}

tinderai.character.user=${USER_PROFILE}