spring.application.name=tinder-ai-backend

spring.ai.openai.base-url=http://127.0.0.1:11434/v1
spring.ai.openai.chat.model=llama3.2:3b
spring.ai.openai.api-key=ollama-local-key

puter.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InYyIn0.eyJ0IjoidCIsInYiOiIyIiwidG9rZW5fdWlkIjoiZWVhMDg3MjItM2EwYi00MGI5LTk2MmItMWZjZmQ5ZjMwYjQzIiwidXUiOiJwbWlDUUNsclNHaTJCM3pidVg2c0NRPT0iLCJzdSI6InN0bVJqN0p3UmlHZDlQQWhvR1NvdFE9PSIsImFpIjoicG1pQ1FDbHJTR2kyQjN6YnVYNnNDUT09IiwiZnVsbF9hY2Nlc3MiOnRydWUsImlhdCI6MTc4NDE5NjMwMSwiZXhwIjoxNzkxOTcyMzAxfQ.Pqx76Lxh4ncLwPDcidC82jkHR7vx5QFBW2CCIqc_jNU

startup-actions.initializeProfiles=false
tinderai.lookingForGender=FEMALE
tinderai.minAge=20
tinderai.maxAge=30
tinderai.ethnicities=Kashmiri,Dogra,Ladakhi,Pahari,Punjabi,Haryanvi,Rajasthani,Uttar_Pradeshi,Bihari,Bhojpuri,Maithili,Bundelkhandi,Chhattisgarhi,Gujarati,Marathi,Goan,Odia,Bengali,Assamese,Manipuri,Mizo,Naga,Khasi,Garo,Tripuri,Sikkimese,Kannadiga,Malayali,Telugu,Tamilian,Tuluva,Kodava

# User's profile
tinderai.character.user={id: 'user', firstName: 'Pravat', lastName: 'Mishra', age: '26', ethnicity: 'Indian', gender: 'MALE', bio: 'Software engineer and learner. I like reading and making things.', imageUrl: 'default.jpg', myersBriggsPersonalityType: 'INTP'}

# MongoDB connection string
# mongodb://root:secret@localhost:- 27017/mydatabase?authSource=admin
